### ISSUE TITLE
Not working a SIM-card.

### ISSUE THREAD

**Issue by MISTAR-HAMSTER** [droidian-devices/adaptation-droidian-lavender#1]
Installed from UBports installer, mobile provider: Phoenix, SIM-card installed in first slot.

**Comment by MISTAR-HAMSTER** [comment]
I apologize for clogging up the problem tracker, everything works. Just had to remove the SD-card and in its place insert the Ukrainian SIM-card MTS

**Comment by erikinkinen** [comment]
Yes, only SIM1 is being used. SIM2 is disabled by oFono configuration because phosh only supports one SIM. Unfortunately,   it is quite common that SIM1 may be a dual slot for either a SIM- or SD-card, not both. This is a design decision made by phone manufacturers to conserve physical space inside these phones. I think it could be possible to change the enabled SIM in the adaptation package so that both a SD and a SIM would be usable at the same time.

**Comment by erikinkinen** [comment]
If https://github.com/droidian-devices/adaptation-droidian-lavender/pull/2 gets merged, it will use the other non-hybrid slot.
